version: "2"

run:
  timeout: 10m

severity:
  default: "critical"

formatters:
  enable:
    - gofmt     # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification.
    - goimports # Check import statements are formatted according to the 'goimport' command.

  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

linters:
  default: none
  enable:
    - asciicheck                # Checks that all code identifiers does not have non-ASCII symbols in the name.
    - bidichk                   # Checks for dangerous unicode character sequences.
    - bodyclose                 # Checks whether HTTP response body is closed successfully.
    - canonicalheader           # Canonicalheader checks whether net/http.Header uses canonical header.
    - contextcheck              # Check whether the function uses a non-inherited context.
    - copyloopvar               # Copyloopvar is a linter detects places where loop variables are copied.
    - durationcheck             # Check for two durations multiplied together.
    - errcheck                  # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - errname                   # Checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error.
    - errorlint                 # Errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - funcorder                 # Checks the order of functions, methods, and constructors.
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid.
    - gocognit                  # Computes and checks the cognitive complexity of functions.
    - goconst                   # Finds repeated strings that could be replaced by a constant.
    - gocritic                  # Provides diagnostics that check for bugs, performance and style issues.
    - goheader                  # Checks if file header matches to pattern.
    - gosec                     # Inspects source code for security problems.
    - govet                     # Vet examines Go source code and reports suspicious constructs.
    - ineffassign               # Detects when assignments to existing variables are not used.
    - makezero                  # Finds slice declarations with non-zero initial length.
    - mnd                       # An analyzer to detect magic numbers.
    - nakedret                  # Checks that functions with naked returns are not longer than a maximum size (can be zero).
    - nilnil                    # Checks that there is no simultaneous return of nil error and an invalid value.
    - noctx                     # Finds sending http request without context.Context.
    - nolintlint                # Reports ill-formed or insufficient nolint directives.
    - nosprintfhostport         # Checks for misuse of Sprintf to construct a host with port in a URL.
    - perfsprint                # Checks that fmt.Sprintf can be replaced with a faster alternative.
    - prealloc                  # Finds slice declarations that could potentially be pre-allocated.
    - revive                    # Fast, configurable, extensible, flexible, and beautiful linter for Go.
    - staticcheck               # It's a set of rules from staticcheck.
    - testpackage               # Linter that makes you use a separate _test package.
    - unconvert                 # Remove unnecessary type conversions.
    - unused                    # Checks Go code for unused constants, variables, functions and types.
    - usetesting                # Reports uses of functions with replacement inside the testing package.
    - usestdlibvars             # A linter that detect the possibility to use variables/constants from the Go standard library.
    - wastedassign              # Finds wasted assignment statements.

  exclusions:
    rules:
      - text: 'Error return value of .((os\.)?std(out|err)\..*|.*print(f|ln)?). is not checked'
        linters: [ errcheck ]
      - path: (.+)_test\.go
        linters: [ gocognit, mnd ]

  settings:
    gocognit:
      min-complexity: 10

    goconst:
      min-len: 2
      min-occurrences: 2

    gocritic:
      disable-all: true
      enabled-checks:
        ## DIAGNOSTIC
        - appendAssign          # Detects suspicious append result assignments.
        - argOrder              # Detects suspicious arguments order.
        - badCall               # Detects suspicious function calls.
        - badCond               # Detects suspicious condition expressions.
        - badLock               # Detects suspicious mutex lock/unlock operations.
        - badRegexp             # Detects suspicious regexp patterns.
        - badSorting            # Detects bad usage of sort package.
        - badSyncOnceFunc       # Detects bad usage of sync.OnceFunc.
        - builtinShadowDecl     # Detects top-level declarations that shadow the predeclared identifiers.
        - caseOrder             # Detects erroneous case order inside switch statements.
        - codegenComment        # Detects malformed ‘code generated’ file comments.
        - commentedOutCode      # Detects commented-out code inside function bodies.
        - deferInLoop           # Detects loops inside functions that use defer.
        - deprecatedComment     # Detects malformed ‘deprecated’ doc-comments.
        - dupArg                # Detects suspicious duplicated arguments.
        - dupBranchBody         # Detects duplicated branch bodies inside conditional statements.
        - dupCase               # Detects duplicated case clauses inside switch or select statements.
        - dupSubExpr            # Detects suspicious duplicated sub-expressions.
        - dynamicFmtString      # Detects suspicious formatting strings usage.
        - emptyDecl             # Detects suspicious empty declarations blocks.
        - evalOrder             # Detects unwanted dependencies on the evaluation order.
        - exitAfterDefer        # Detects calls to exit/fatal inside functions that use defer.
        - externalErrorReassign # Detects suspicious reassignment of error from another package.
        - filepathJoin          # Detects problems in filepath.Join() function calls.
        - flagDeref             # Detects immediate dereferencing of flag package pointers.
        - flagName              # Detects suspicious flag names.
        - mapKey                # Detects suspicious map literal keys.
        - nilValReturn          # Detects return statements those results evaluate to nil.
        - offBy1                # Detects various off-by-one kind of errors.
        - rangeAppendAll        # Detects append all its data while range it.
        - regexpPattern         # Detects suspicious regexp patterns.
        - returnAfterHttpError  # Detects suspicious http.Error call without following return.
        - sloppyLen             # Detects usage of len when result is obvious or doesn’t make sense.
        - sloppyReassign        # Detects suspicious/confusing re-assignments.
        - sloppyTypeAssert      # Detects redundant type assertions.
        - sortSlice             # Detects suspicious sort.Slice calls.
        - sprintfQuotedString   # Detects “%s” formatting directives that can be replaced with %q.
        - sqlQuery              # Detects issue in Query() and Exec() calls.
        - syncMapLoadAndDelete  # Detects sync.Map load+delete operations that can be replaced with LoadAndDelete.
        - truncateCmp           # Detects potential truncation issues when comparing ints of different sizes.
        - uncheckedInlineErr    # Detects unchecked errors in if statements.
        - unnecessaryDefer      # Detects redundantly deferred calls.
        - weakCond              # Detects conditions that are unsafe due to not being exhaustive.

        ## STYLE
        - assignOp                 # Detects assignments that can be simplified by using assignment operators.
        - boolExprSimplify         # Detects bool expressions that can be simplified.
        - builtinShadow            # Detects when predeclared identifiers are shadowed in assignments.
        - captLocal                # Detects capitalized names for local variables.
        - commentFormatting        # Detects comments with non-idiomatic formatting.
        - commentedOutImport       # Detects commented-out imports.
        - defaultCaseOrder         # Detects when default case in switch isn’t on 1st or last position.
        - deferUnlambda            # Detects deferred function literals that can be simplified.
        - docStub                  # Detects comments that silence go lint complaints about doc-comment.
        - dupImport                # Detects multiple imports of the same package under different aliases.
        - elseif                   # Detects else with nested if statement that can be replaced with else-if.
        - emptyFallthrough         # Detects fallthrough that can be avoided by using multi case values.
        - emptyStringTest          # Detects empty string checks that can be written more idiomatically.
        - exposedSyncMutex         # Detects exposed methods from sync.Mutex and sync.RWMutex.
        - hexLiteral               # Detects hex literals that have mixed case letter digits.
        - httpNoBody               # Detects nil usages in http.NewRequest calls, suggesting http.NoBody as an alternative.
        - ifElseChain              # Detects repeated if-else statements and suggests to replace them with switch statement.
        - importShadow             # Detects when imported package names shadowed in the assignments.
        - initClause               # Detects non-assignment statements inside if/switch init clause.
        - methodExprCall           # Detects method expression call that can be replaced with a method call.
        - nestingReduce            # Finds where nesting level could be reduced.
        - newDeref                 # Detects immediate dereferencing of new expressions.
        - octalLiteral             # Detects old-style octal literals.
        - paramTypeCombine         # Detects if function parameters could be combined by type and suggest the way to do it.
        - preferFilepathJoin       # Detects concatenation with os.PathSeparator which can be replaced with filepath.Join.
        - ptrToRefParam            # Detects input and output parameters that have a type of pointer to referential type.
        - redundantSprint          # Detects redundant fmt.Sprint calls.
        - regexpMust               # Detects regexp.Compile* that can be replaced with regexp.MustCompile*.
        - regexpSimplify           # Detects regexp patterns that can be simplified.
        - singleCaseSwitch         # Detects switch statements that could be better written as if statement.
        - stringConcatSimplify     # Detects string concat operations that can be simplified.
        - stringsCompare           # Detects strings.Compare usage.
        - switchTrue               # Detects switch-over-bool statements that use explicit true tag value.
        - timeExprSimplify         # Detects manual conversion to milli- or microseconds.
        - todoCommentWithoutDetail # Detects TODO comments without detail/assignee.
        # tooManyResultsChecker    # Detects function with too many results.
        - typeAssertChain          # Detects repeated type assertions and suggests to replace them with type switch statement.
        - typeDefFirst             # Detects method declarations preceding the type definition itself.
        - typeSwitchVar            # Detects type switches that can benefit from type guard clause with variable.
        - typeUnparen              # Detects unneeded parenthesis inside type expressions and suggests to remove them.
        - underef                  # Detects dereference expressions that can be omitted.
        - unlabelStmt              # Detects redundant statement labels.
        - unlambda                 # Detects function literals that can be simplified.
        # unnamedResult            # Detects unnamed results that may benefit from names.
        # unnecessaryBlock         # Detects unnecessary braced statement blocks.
        - unslice                  # Detects slice expressions that can be simplified to sliced expression itself.
        - valSwap                  # Detects value swapping code that are not using parallel assignment.
        # whyNoLint                # Ensures that //nolint comments include an explanation.
        - wrapperFunc              # Detects function calls that can be replaced with convenience wrappers.
        - yodaStyleExpr            # Detects Yoda style expressions and suggests to replace them.

        ## PERFORMANCE
        - appendCombine      # Detects append chains to the same slice that can be done in a single append call.
        - equalFold          # Detects unoptimal strings/bytes case-insensitive comparison.
        # hugeParam          # Detects params that incur excessive amount of copying.
        - indexAlloc         # Detects strings.Index calls that may cause unwanted allocs.
        - preferDecodeRune   # Detects expressions like []rune(s)[0] that may cause unwanted rune slice allocation.
        - preferFprint       # Detects fmt.Sprint(f/ln) calls which can be replaced with fmt.Fprint(f/ln).
        - preferStringWriter # Detects w.Write or io.WriteString calls which can be replaced with w.WriteString.
        - preferWriteByte    # Detects WriteRune calls with rune literal argument that is single byte and reports to use WriteByte instead.
        - rangeExprCopy      # Detects expensive copies of for loop range expressions.
        - rangeValCopy       # Detects loops that copy big objects during each iteration.
        - sliceClear         # Detects slice clear loops, suggests an idiom that is recognized by the Go compiler.
        - stringXbytes       # Detects redundant conversions between string and []byte.

    goheader:
      template-path: ../.github/goheader.tmpl

    gosec:
      excludes:
        # _ instead of err checks
        - G104

    govet:
      enable-all: true

    nakedret:
      max-func-lines: 10

    nilnil:
      detect-opposite: true

    nolintlint:
      require-specific: true

    prealloc:
      range-loops: true

    revive:
      severity: error
      rules:
        - name: atomic                # Check for commonly mistaken usages of the sync/atomic package.
        - name: confusing-naming      # Methods or fields of struct that have names different only by capitalization could be confusing.
        - name: confusing-results     # Function or methods that return multiple, no named, values of the same type could induce error.
        - name: constant-logical-expr # The rule spots logical expressions that evaluate always to the same value.
        - name: context-keys-type     # Basic types should not be used as a key in context.WithValue.
        - name: deep-exit             # Packages exposing functions that can stop program execution by exiting are hard to reuse. This rule looks for program exits in functions other than main() or init().
        - name: early-return          # In GO it is idiomatic to minimize nesting statements, a typical example is to avoid if-then-else constructions.
        - name: empty-block           # Empty blocks make code less readable and could be a symptom of a bug or unfinished refactoring.
        - name: empty-lines           # Sometimes gofmt is not enough to enforce a common formatting of a code-base; this rule warns when there are heading or trailing newlines in code blocks.
        - name: error-return          # By convention, for the sake of readability, the errors should be last in the list of returned values by a function.
        - name: error-strings         # By convention, for better readability, error messages should not be capitalized or end with punctuation or a newline.
        - name: errorf                # It is possible to get a simpler program by replacing errors.New(fmt.Sprintf()) with fmt.Errorf(). This rule spots that kind of simplification opportunities.
        - name: identical-branches    # An if-then-else conditional with identical implementations in both branches is an error.
        - name: if-return             # Checking if an error is nil to just after return the error or nil is redundant.
        - name: increment-decrement   # By convention, for better readability, incrementing an integer variable by 1 is recommended to be done using the ++ operator. This rule spots expressions like i += 1 and i -= 1 and proposes to change them into i++ and i--.
        - name: range                 # This rule suggests a shorter way of writing ranges that do not use the second value.
        - name: redefines-builtin-id  # Constant names like false, true, nil, function names like append, make, and basic type names like bool, and byte are not reserved words of the language; therefore the can be redefined. Even if possible, redefining these built in names can lead to bugs very difficult to detect.
        - name: redundant-build-tag   # This rule warns about redundant build tag comments // +build when //go:build is present. gofmt in Go 1.17+ automatically adds the //go:build constraint, making the // +build comment unnecessary.
        - name: string-of-int         # Explicit type conversion string(i) where i has an integer type other than rune might behave not as expected by the developer (e.g. string(42) is not "42"). This rule spot that kind of suspicious conversions.
        - name: use-any               # Since Go 1.18, interface{} has an alias: any. This rule proposes to replace instances of interface{} with any.
        - name: use-errors-new        # This rules identifies calls to fmt.Errorf that can be safely replaced by, the more efficient, errors.New.
        - name: unnecessary-stmt      # This rule suggests to remove redundant statements like a break at the end of a case block, for improving the code's readability.
        - name: unreachable-code      # This rule spots and proposes to remove unreachable code.
        - name: waitgroup-by-value    # Function parameters that are passed by value, are in fact a copy of the original argument. Passing a copy of a sync.WaitGroup is usually not what the developer wants to do. This rule warns when a sync.WaitGroup expected as a by-value parameter in a function or method.

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
